### ISSUE TITLE
Error with example?

### ISSUE THREAD

**Issue by ellisakins** [electricimp/SPIFlashFileSystem#8] opened 2016-01-29 21:53 UTC
Hello, I am trying to use the example for a larger foundation and have some issues. Attached are some logs. I copy pasted the code from the example and got a few errors. I attached logs. First I get:

ERROR: null cannot be used as index
2016-01-29 16:41:13 UTC-5   [Device]    ERROR:   in constructor ...lashfilesystem.class.nut#1.0.0:713
2016-01-29 16:41:13 UTC-5   [Device]    ERROR:   from init ...lashfilesystem.class.nut#1.0.0:95
2016-01-29 16:41:13 UTC-5   [Device]    ERROR:   from main device_code:8

so I changed line 7 to "spiffs <- SPIFlashFileSystem(0x000000, 0x300000);" to include boundaries (I guess). Seemed to fix that error. Then, the code runs, and keeps gathering data from the get request, seeming to run forever until I get another error about the garbage collector not existing (I assume). 

I hope I did not do something wrong and waste anyone's time. Thanks.

[errorlog_sffschuckexample_github.txt](https://github.com/electricimp/SPIFlashFileSystem/files/110472/errorlog_sffschuckexample_github.txt)

**Comment by ellisakins** [comment] 2016-01-29 21:55
Agent and device codes

[sffsexample_issue_agent.txt](https://github.com/electricimp/SPIFlashFileSystem/files/110478/sffsexample_issue_agent.txt)
[sffsexample_issue_device.txt](https://github.com/electricimp/SPIFlashFileSystem/files/110477/sffsexample_issue_device.txt)

**Comment by blindman2k** [comment] 2016-01-29 22:10
What hardware are you running this on?

**Comment by ellisakins** [comment] 2016-01-29 22:11
Imp003

**Comment by blindman2k** [comment] 2016-01-29 22:18
I can reproduce those errors. I will fix them as soon as I finish flogging myself :cry: (before Monday).

**Comment by ellisakins** [comment] 2016-01-29 22:19
Don't go to hard on yourself. It will be impressive when working :)

**Comment by blindman2k** [comment] 2016-01-29 22:20
I have it working but off a slightly different branch and added some bugs when I converted into a library.

**Comment by blindman2k** [comment] 2016-01-29 22:50
The first error was caused by using a SPIFlash with random data already on it. 
Erase the existing data on the flash by adding `spiffs.eraseAll()` before init. Run once then remove it.

``` squirrel
spiffs <- SPIFlashFileSystem();
spiffs.eraseAll();
spiffs.init();
```

I will improve the code's handling of this situation.

**Comment by ellisakins** [comment] 2016-01-29 23:48
Ah. I thought init() had to be called before any other function. Also saw this, thought it might be of use:

2016-01-29 18:40:43 UTC-5   [Device]    ERROR: the index 'len' does not exist
2016-01-29 18:40:43 UTC-5   [Device]    ERROR:   in _writePage ...lashfilesystem.class.nut#1.0.0:438
2016-01-29 18:40:43 UTC-5   [Device]    ERROR:   from _write ...lashfilesystem.class.nut#1.0.0:381
2016-01-29 18:40:43 UTC-5   [Device]    ERROR:   from write ...lashfilesystem.class.nut#1.0.0:1054
2016-01-29 18:40:43 UTC-5   [Device]    ERROR:   from unknown device_code:148
2016-01-29 18:40:43 UTC-5   [Device]    ERROR:   from unknown ...imp#bullwinkle.class.nut#2.0.1:231

edit, i got those when using the sffs on some other code, not sure if that's anything to do with it, thanks

**Comment by blindman2k** [comment] 2016-01-30 02:46
Generally it does but eraseAll() wipes everything including the FAT.
That new error is because you have an empty filename. Can you send me the new code you are using.

**Comment by blindman2k** [comment] 2016-01-30 03:22
I have added some error checking and tweaked the example a bit. Just got to wait for the pull request to be approved.

**Comment by betzrhodes** [comment] 2016-01-30 03:45
Pull request merged.  You can find the latest code on this repo's master branch.  The library version has not been updated yet, so please copy and paste the class.nut file instead of using the require statement.  I'll post a notification here when the library has been updated.

**Comment by ellisakins** [comment] 2016-01-30 05:18
Aron, I was trying to adapt the example to accommodate multiple files, something like this:

<c>files <- {
     "fileidone" : "https://fileurlone.com",
     "fileidtwo" : "https://fileurltwo.com",
}

function formatme() {
        sffs.eraseAll();
    foreach (id,location in files) {
        getNextChunk(id, location));
    }
}

// Function to recursively get the next chunk of the URL until it is finished
function getNextChunk(file = null, fileurl = null, offset = 0, length = 1000) {

```
// Prepare a request packet
local request = {
    "url": fileurl,
    "offset": offset,
    "length": length
}

// Send the request to the agent
bull.send("http.get", request)
    .onReply(

        // We received a response
        function(message) {
            if (message.data) {
                // We have a chunk of data
                if (!filez) filez = spiffs.open(file, "w");

                // Write at the end of the file
                filez.write(message.data)

                // Request the next chunk
                getNextChunk(file, offset + length, length);
            } else {
                // We have finished or there is an error
                if (filez) {
                    // Close the file
                    server.log("Received file of length: " + filez.len())
                    filez.close();
                }
            }
        }

    )

    .onFail(

        // The request timed out or failed, just log and retry
        function(err, message, retry) {
            server.error("Failed get next chunk. Retrying.")
            retry(10);
        }.bindenv(this)

    )
```

}

formatme();<c>

Im pretty sure that its not operating as I want. the foreach runs multiple at one it seems, looking into generators. Maybe bindenv(). Thanks for your help. Got a single file to download and play great (woohoo), now just working on multiple.

**Comment by blindman2k** [comment] 2016-01-30 06:49
You aren't using classes so bindenv isn't going to make a difference. You haven't defined `filez` anywhere. You want to pass that into the getNextChunk function. Try this:

``` squirrel
files <- {
    "fileidone" : "https://fileurlone.com",
    "fileidtwo" : "https://fileurltwo.com",
}

function formatme() {
    sffs.eraseAll();
    foreach (id, location in files) {
        getNextChunk(id, location);
    }
}

// Function to recursively get the next chunk of the URL until it is finished
function getNextChunk(file = null, fileurl = null, offset = 0, length = 1000, filez = null) {

    // Prepare a request packet
    local request = {
        "url": fileurl,
        "offset": offset,
        "length": length
    }

    // Send the request to the agent
    bull.send("http.get", request)
        .onReply(

            // We received a response
            function(message) {
                if (message.data) {
                    // We have a chunk of data
                    if (!filez) filez = spiffs.open(file, "w");

                    // Write at the end of the file
                    filez.write(message.data)

                    // Request the next chunk
                    getNextChunk(file, offset + length, length, filez);
                } else {
                    // We have finished or there is an error
                    if (filez) {
                        // Close the file
                        server.log("Received file of length: " + filez.len())
                        filez.close();
                    }
                }
            }.bindenv(this)

        )

        .onFail(

            // The request timed out or failed, just log and retry
            function(err, message, retry) {
                server.error("Failed get next chunk. Retrying.")
                retry(10);
            }.bindenv(this)

        )
}

formatme();
```

**Comment by betzrhodes** [comment] 2016-02-02 01:41
Library v1.0.2 now updated & released.

**Comment by betzrhodes** [comment] 2016-03-15 23:54
Library v1.1.0 now updated & released

**Closed as completed by betzrhodes** 2016-03-15 23:54 UTC
